version: '3'
services:
  postgres:
    image: postgres:16
    container_name: nestjs-app-postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: nestjs-app-pgadmin
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
  redis:
    image: redis/redis-stack
    container_name: nestjs-app-redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
      - ${REDISINSIGHT_PORT}:8001
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
  mongo:
    image: mongo
    container_name: nestjs-app-mongo
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: --wiredTigerCacheSizeGB 0.25
    volumes:
      - mongo:/data/db
      - mongo-config:/data/configdb
  nestjs-app:
    image: nestjs-app-dev
    build:
      context: .
      target: nestjs-app-dev
      args:
        - PORT:${PORT}
    container_name: nestjs-app-dev
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/nestjs-app/
volumes:
  postgres:
    name: nestjs-app-postgres
  redis:
    name: nestjs-app-redis
  mongo:
    name: nestjs-app-mongo
  mongo-config:
    name: nestjs-app-mongo-config
  pgadmin:
    name: nestjs-app-pgadmin
networks:
  default:
    name: nestjs-app
